INSERT INTO ReportAP (
    PLCID, KODETOC, DCTYPE, CANO, NOTANO, POLICYNO, TTG, ASURANSI, PROFILE_NO, ADATE, 
    DUEDATE, MTU, KURS, NPRM, NPOT, NBRK, PPN, BPLS, BMTR, NFEE, 
    DUEAMOUNT, CO1, NPAYMENT, CLIENTPAID, NAMATOC, NAMACOB, KODECO, 
    VOUCHER, DNVISION, PAYMENT_OC, VOUCHERPAYMENT, MAXPAIDDATE, 
    CERTIFICATE_NO, KODECO2, USRID, COMMPCT
)
SELECT DISTINCT 

    NT.PLCID, NT.KODETOC, NT.DCTYPE, P.CANO, NT.NOTANO, 
    ISNULL(A1.VAL, A3.VAL) AS POLICYNO, 
    CASE 
        WHEN CHARINDEX('BSM', NT.REFF) > 0 THEN 'PT BANK SYARIAH INDONESIA' 
        WHEN CHARINDEX('and/or', P.PLCTTG) > 0 THEN SUBSTRING(P.PLCTTG, 0, CHARINDEX('and/or', P.PLCTTG)) 
        ELSE P.PLCTTG 
    END AS TTG, 
    NT.NAMA AS ASURANSI, PRO.PROFILENO AS PROFILE_NO, 
    NT.ADATE, FP.DUEDATE, FP.MTU, FP.KURS, FP.NPRM, FP.NPOT, FP.NBRK, FP.PPN, 
    FP.BPLS, FP.BMTR, FP.NFEE, FP.DUEAMOUNT, A2.VAL AS CO1, FP.NPAYMENT,
    FP.ISPAID AS CLIENTPAID, TOC.NAMATOC, COB.NAMACOB, CO.KODECO, 
    FP.VOUCHER, ISNULL(A4.VAL, A5.VAL) AS DNVISION, 
    FP.PAYMENT_OC, PY.VOUCHERPAYMENT, PY.MAXPAIDDATE, A6.VAL AS CERTIFICATE_NO, 
    A7.VAL AS KODECO2, CO.USRID, CAST(A8.VAL AS DECIMAL(5,2)) AS COMMPCT 
FROM TALYS.dbo.FAPAYMENT FP WITH (NOLOCK)
INNER JOIN TALYS.dbo.FAVOUCHER VO WITH (NOLOCK) ON FP.VOUCHER = VO.VOUCHER 
INNER JOIN TALYS.dbo.PLCNOTA NT WITH (NOLOCK) ON NT.NOTANO = VO.NOTANO 
INNER JOIN TALYS.dbo.PROFILE PRO WITH (NOLOCK) ON PRO.PROFILEID = NT.PROFILEID 
LEFT OUTER JOIN TALYS.dbo.PLACING P WITH (NOLOCK) ON P.PLCID = NT.PLCID 
LEFT OUTER JOIN TALYS.dbo.PLACINGTOC PLCTOC WITH (NOLOCK) ON PLCTOC.PLCID = NT.PLCID AND NT.KODETOC = PLCTOC.KODETOC 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A1 WITH (NOLOCK) ON A1.PLCID = NT.PLCID AND A1.CONFIGID = 'POLICY_NO' AND PLCTOC.URUT = 1 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A3 WITH (NOLOCK) ON A3.PLCID = NT.PLCID AND A3.CONFIGID = 'POLICY_NO2' AND PLCTOC.URUT = 2 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A2 WITH (NOLOCK) ON A2.PLCID = NT.PLCID AND A2.CONFIGID = 'PS_PIC_MKT' 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A4 WITH (NOLOCK) ON A4.PLCID = NT.PLCID AND A4.CONFIGID = 'DN_VISION' AND PLCTOC.URUT = 1 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A5 WITH (NOLOCK) ON A5.PLCID = NT.PLCID AND A5.CONFIGID = 'DN_VISION2' AND PLCTOC.URUT = 2 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A6 WITH (NOLOCK) ON A6.PLCID = NT.PLCID AND A6.CONFIGID = 'CERTIFICATE_NO' 
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A7 WITH (NOLOCK) ON A7.PLCID = NT.PLCID AND A7.CONFIGID = 'PS_PIC_MKT2'  
LEFT OUTER JOIN TALYS.dbo.PLCADDINFO A8 WITH (NOLOCK) ON A8.PLCID = NT.PLCID AND A8.CONFIGID = 'BROKERAGE_PCT'  
INNER JOIN TALYS.dbo.MSTTOC TOC WITH (NOLOCK) ON TOC.KODETOC = NT.KODETOC 
INNER JOIN TALYS.dbo.MSTCOB COB WITH (NOLOCK) ON TOC.KDTNEW1 = COB.KODECOB 
LEFT OUTER JOIN TALYS.dbo.CO WITH (NOLOCK) ON CO.USRID = A2.VAL
--LEFT OUTER JOIN CO ON CO.USRID = A2.VAL 
LEFT OUTER JOIN (
    SELECT DOCNO, 
        STUFF((SELECT ', ' + t.voucher 
               FROM TALYS.dbo.FAPAYMENTD t WITH (NOLOCK)
               WHERE t.docno = t1.docno 
               ORDER BY t.voucher 
               FOR XML PATH('')), 1, 1, '') AS VOUCHERPAYMENT, 
        MAX(PAIDDATE) AS MAXPAIDDATE 
    FROM TALYS.dbo.FAPAYMENTD t1 WITH (NOLOCK)
    GROUP BY DOCNO
) PY ON PY.DOCNO = FP.VOUCHER
WHERE (NT.DCTYPE IN ('DI', 'CF') OR (NT.DCTYPE = 'OP' AND NT.DC = 'C')) 
ORDER BY NT.NOTANO;

