  SELECT P.PLCID, P.PLCNO, P.CANO, NTD.NOTANO,
    CASE WHEN CHARINDEX('and/or', P.PLCTTG) > 0 THEN SUBSTRING(P.PLCTTG, 0, CHARINDEX('and/or', P.PLCTTG)) ELSE P.PLCTTG END AS TTG, 
    P.BSMID, P.BANKID, BANK.NAMA AS BANK, ISNULL(INS.NAMA, MINS.NAMA) AS ASURANSI, 
    TOC.KODETOC, TOC.NAMATOC, P.SDATE, P.EDATE, A.ADATE, P.STATUS,
    'IDR' AS MTU, 1 AS KURS, 
    A.DPRM, A.DPOT, A.DPLS, A.DMTR, A.DBRK, A.DPPN, A.DTOTAL,
    A.CPRM, A.CPOT, A.CPLS, A.CMTR, A.CBRK, A.CPPN, A.CTOTALBRK, A.CTOTAL, A.FEEBANK, A.NETT,
    ISNULL(A1.VAL, A7.VAL) AS POLICYNO, A2.VAL AS CO1, A6.VAL AS CO2, FL.SECUSER AS PLCUSER, A3.VAL AS PARTICULAR, 
    ISNULL(A4.VAL, A5.VAL) AS DNVISION
  FROM PLACING P
  LEFT OUTER JOIN PLCINSURANCE INS ON INS.PLCID = P.PLCID AND INS.TYPEF = 'L'
  LEFT OUTER JOIN PLCINSURANCE MINS ON MINS.PLCID = P.MPLCID AND MINS.TYPEF = 'L'
  LEFT OUTER JOIN PROFILE BANK ON P.BANKID = BANK.PROFILEID
  LEFT OUTER JOIN PLCFLOW FL ON FL.PLCID = P.PLCID AND FL.URUT = 1
  INNER JOIN (
    SELECT C.PLCID, C.KODETOC, C.ADATE, C.ARAPID,
      SUM(C.NPRM*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DPRM, 
      SUM(C.NPOT*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DPOT, 
      SUM(C.BPLS*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DPLS, 
      SUM(C.BMTR*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DMTR, 
      SUM(C.NBRK*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DBRK, 
      SUM(C.NPPN*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DPPN,      
      SUM((C.TTLTGH+C.TTLBRK)*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) AS DTOTAL,
      SUM(C.NPRM*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CPRM, 
      SUM(C.NPOT*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CPOT, 
      SUM(C.BPLS*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CPLS, 
      SUM(C.BMTR*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CMTR, 
      SUM(C.NBRK*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CBRK, 
      SUM(C.NPPN*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CPPN, 
      SUM(C.TTLBRK*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CTOTALBRK,
      SUM((C.TTLTGH+C.TTLBRK)*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0)) AS CTOTAL,
      SUM(C.NFEE*C.KURS*IIF(C.DCTYPE = 'BF', 1, 0)) AS FEEBANK,
      SUM(((C.TTLTGH+C.TTLBRK)*C.KURS*IIF(C.DCTYPE = 'BB', 1, 0)) 
        - ((C.TTLTGH+C.TTLBRK)*C.KURS*IIF(C.DCTYPE IN ('DI','CF'), 1, 0))
        + (C.NFEE*C.KURS*IIF(C.DCTYPE = 'BF', 1, 0))) AS NETT
    FROM PLCNOTA C
    WHERE --NOT EXISTS (SELECT 1 FROM PLCNOTA COUT WHERE COUT.NOTANO IS NULL AND C.PLCID = COUT.PLCID) AND 
    (C.NOTANO IS NOT NULL) AND (C.ARAPID IS NOT NULL)
    AND EXISTS (SELECT 1 FROM FAVOUCHER V WHERE C.NOTANO = V.NOTANO)
    GROUP BY C.PLCID, C.KODETOC, C.ADATE, C.ARAPID) A ON A.PLCID = P.PLCID
  INNER JOIN PLACINGTOC PLCTOC ON PLCTOC.PLCID = P.PLCID AND A.KODETOC = PLCTOC.KODETOC
  INNER JOIN MSTTOC TOC ON TOC.KODETOC = A.KODETOC
  LEFT OUTER JOIN PLCADDINFO A1 ON (A1.PLCID = P.PLCID) AND (A1.CONFIGID = 'POLICY_NO') AND (PLCTOC.URUT = 1)
  LEFT OUTER JOIN PLCADDINFO A7 ON (A7.PLCID = P.PLCID) AND (A7.CONFIGID = 'POLICY_NO2') AND(PLCTOC.URUT = 2)
  LEFT OUTER JOIN PLCADDINFO A2 ON (A2.PLCID = P.PLCID) AND (A2.CONFIGID = 'PS_PIC_MKT')
  LEFT OUTER JOIN PLCADDINFO A3 ON A3.PLCID = P.PLCID AND A3.CONFIGID = 'PARTICULAR'
  LEFT OUTER JOIN PLCADDINFO A6 ON (A6.PLCID = P.PLCID) AND (A6.CONFIGID = 'PS_PIC_MKT2')
  LEFT OUTER JOIN PLCADDINFO A4 ON (A4.PLCID = P.PLCID) AND (A4.CONFIGID = 'DN_VISION') AND (PLCTOC.URUT = 1)
  LEFT OUTER JOIN PLCADDINFO A5 ON (A5.PLCID = P.PLCID) AND (A5.CONFIGID = 'DN_VISION2') AND (PLCTOC.URUT = 2)
  INNER JOIN (SELECT NOTANO, PLCID, KODETOC, ARAPID, ROW_NUMBER() OVER (PARTITION BY PLCID, KODETOC, ARAPID ORDER BY NOTANO) AS RowFilter FROM PLCNOTA WHERE DCTYPE = 'BB' AND DC = 'D') NTD 
      ON NTD.PLCID = A.PLCID AND NTD.KODETOC = A.KODETOC AND NTD.RowFilter = 1 AND NTD.ARAPID = A.ARAPID


